### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by koppor** [p-groarke/wsay#1]
Would it be possible to creat a chocolatey package? AS user, I'd like to execute following command to have wsay installed

    choco install wsay

https://chocolatey.org/docs/create-packages.

I know, it's a bit overhead for one `.exe`, but it would help to include the tool in installations for tools such as [mob](https://github.com/remotemobprogramming/mob/#tool-for-remote-mob-programming).

**Comment by p-groarke** [comment]
Usually package managers like chocolatey maintain their own releases. If the chocolatey folks want to add wsay to their manager that would be great, but I won't be doing so myself.

**Comment by p-groarke** [comment]
Closing this as it is inactive. Feel free to reopen if the nice chocolatey folks want to add this project and need something from me :)

**Comment by koppor** [comment]
It will be you or me making the package. Since you already rejected it and I have (currently) no time, we need to wait for me gaining some time or some open source volunteer person doing it. (Anyone can submit a chocolatey package)
