### ISSUE TITLE
Missing --rate option

### ISSUE THREAD

**Issue by 60-hz** [p-groarke/wsay#10]
Great, would be nice to have the rate function also.

Cheers

**Comment by p-groarke** [comment]
@60-hz  When you say `rate`, do you mean sample-rate or voice speed (or something else)?

**Comment by 60-hz** [comment]
@p-groarke Sorry, I was speaking about voice speed, which is an interesting function for speech synthesis.

**Comment by p-groarke** [comment]
@60-hz You got it 👍 
https://github.com/p-groarke/wsay/releases/tag/v1.4.3
