### ISSUE TITLE
Build error on windows 8

### ISSUE THREAD

**Issue by mitmelon** [p-groarke/wsay#11]
Getting this error from cmake

CMake Error at CMakeLists.txt:121 (find_package):
  Could not find a package configuration file provided by "nuklear" with any
  of the following names:

    nuklearConfig.cmake
    nuklear-config.cmake

  Add the installation prefix of "nuklear" to CMAKE_PREFIX_PATH or set
  "nuklear_DIR" to a directory containing one of the above files.  If
  "nuklear" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by p-groarke** [comment]
Hey there, I could remove that dependency since it was for an experiment, but first. Do you have conan installed? Did it pull nuklear correctly?

Note that, Windows 8 hasn't been tested (and won't be by me), but I can try to help.

**Comment by mitmelon** [comment]
> Hey there, I could remove that dependency since it was for an experiment, but first. Do you have conan installed? Did it pull nuklear correctly?
> 
> Note that, Windows 8 hasn't been tested (and won't be by me), but I can try to help.

Yes I have installed conan.

**Comment by p-groarke** [comment]
What is it's output? You can run the conan command manually as well to see. The problem you're having is very likely conan related.

**Comment by mitmelon** [comment]
> nuklear"

Okay its now working... I removed nuklear from cmake file just as you said and it built successfully.

Thanks for your help. 

Do you have any idea on how to download more voices on windows 8.1?

**Comment by p-groarke** [comment]
Yeah that I don't think is possible. You'd have to check microsoft docs, but AFAIK it's a Windows 10 thing.

Glad it's fixed! Just don't build the GUI experiment and you should be gtg. I'll take a look at conan nuklear this w-e, maybe they've changed the package or something.

I'll close this issue, feel free to reopen if you have more problems

**Comment by mitmelon** [comment]
> Yeah that I don't think is possible. You'd have to check microsoft docs, but AFAIK it's a Windows 10 thing.
> 
> Glad it's fixed! Just don't build the GUI experiment and you should be gtg. I'll take a look at conan nuklear this w-e, maybe they've changed the package or something.
> 
> I'll close this issue, feel free to reopen if you have more problems

Okay thanks...
