### ISSUE TITLE
How to add voices?

### ISSUE THREAD

**Issue by eabase** [p-groarke/wsay#17]
Hi, cool app. 
In the docs there are some Australian voices, but on my machine they are not present, only US ones.   
What's going on and how can I add other voices?

**Comment by p-groarke** [comment]
Hey @eabase , glad you like it.

You install new voices through windows itself (Win11 : Add Speech Voices > Manage voices). They should appear next time you list the voices.

Here's a guide I found for win10 : https://www.majorgeeks.com/content/page/how_to_add_and_remove_speech_voices_in_windows_10.html

I'll mark this as closed, but please reopen if you have issues.
Cheers

**Comment by p-groarke** [comment]
Oh and I'll add some intructions to readme next time I update it :)

**Comment by eabase** [comment]
I think I found it.  

1. Type: **`[WIN]+[CTRL]+N`**, then click on the text `Add more voices`. 

![image](https://user-images.githubusercontent.com/52289379/208253998-f25ef8cb-9e93-4498-a761-ff9066a9c89b.png)

2. Scroll down to `Add voices`:

![image](https://user-images.githubusercontent.com/52289379/208254125-d076c5ab-8ac0-443d-9b97-e0162a4fc419.png)

---

Would have been cool if there's a powershell command to do this...

**Comment by eabase** [comment]
> Oh and I'll add some instructions to readme next time I update it :)


Great. You copy paste the above maybe.

**Comment by p-groarke** [comment]
I'll search around for a terminal / powershell way to load the settings. If I can't find it, the shortcut is nice. 👍

**Comment by eabase** [comment]
I just noticed that any windows update will break your old registry items for voice tokens when adding voices. Fortunately I exported my old registry items, and I could easily re-instate the items with:

```powershell
function fun {
  $regfile = [IO.Path]::GetFileName("$args[0]")
  $argslist =  @("/s", "`"C:\$regfile`"")	# Silently (/s) import regedit file: <regfile.reg>
  Start-Process -filepath "$Env:SystemRoot\regedit.exe" -Argumentlist $argslist -Verb RunAs -PassThru -Wait
# Reload registry...
}
```

**Comment by p-groarke** [comment]
@eabase Hi again!

I'm curious what you mean by that? I've updated Windows often here and it was OK... Do you mean there is a new update that breaks all the voices (moves the registry entries for example)?

**Comment by eabase** [comment]
> I'm curious what you mean by that? I've updated Windows often here and it was OK... Do you mean there is a new update that breaks all the voices (moves the registry entries for example)?

Yep, that's exactly what happened. After I updated my Win-11 to 24H2, it seem to have reverted the registry items. I have yet to determine what else it broke, apart from also force installing the Tobii malware that clandestinely uploads facial recognition data to *their own servers*...

**Comment by p-groarke** [comment]
Lol at Tobii malware 🤦 

OK thank you for the heads up! I'm going to update whenever I can and see how that goes. Updating registery should be simple, tbd. Could be a MS bug, could be they changed the location. Cheers and take care!
