### ISSUE TITLE
Could not speak multiple words

### ISSUE THREAD

**Issue by senpa1-13** [p-groarke/wsay#18]
Hello! I was trying to make a text to speech robot in VS code but it doesn't generated the result that I wanted.
Its working fine for single words but could not speak multiple words of a sentence. Why?

**### Edit: I added comma in between the words and its working fine now**

![issue](https://user-images.githubusercontent.com/92083101/229773173-38352805-2a78-460c-b73f-047dd2144877.png)

**Comment by p-groarke** [comment]
Glad it's working!
