### ISSUE TITLE
Is this usable Commercially?

### ISSUE THREAD

**Issue by Zeddesnetos** [p-groarke/wsay#19]

**Comment by p-groarke** [comment]
Absolutely it is. You can read the license regarding the terms of binary distribution : https://github.com/p-groarke/wsay/blob/master/license

Basically, in the software you ship, that license must be somewhere. Often, commercial software ships with an `attribution.txt`  where it lists all the licenses and attributions of open-source libraries it uses. AFAIK that fulfills this license fully (BSD3).

**Comment by Zeddesnetos** [comment]
Okey, thanks for the info :)
