### ISSUE TITLE
Problem while using it through vs code.

### ISSUE THREAD

**Issue by Mukul-Nirwal** [p-groarke/wsay#24]
Hi there ,
Actually I am a beginner , I am making a project called robo speaker by python in VS Code . 

It is showing : ( _'wsay' is not recognized as an internal or external command, operable program or batch file_. )

**please guide me through proper steps .**

Or if possible if you have any python source code for this kind of project please share . 

![Screenshot (186)](https://github.com/p-groarke/wsay/assets/163006680/7e0445e7-bc15-4a99-8521-3cdb69934d48)

**Comment by p-groarke** [comment]
Sorry this is outside of the typical usage for `wsay`. I'd take a look at some python examples running command line tools and vs code stuff.

Best of luck! :)

**Comment by Mukul-Nirwal** [comment]
> Sorry this is outside of the typical usage for `wsay`. I'd take a look at some python examples running command line tools and vs code stuff.
> 
> Best of luck! :)

ok thank you 
I think I need to code this with another method
