### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Samthapa76** [p-groarke/wsay#26]
is there way to use this 

wsay.exe > "strings"  ? 

c:\wsay.exe > "strings" direct way ?

**Comment by p-groarke** [comment]
Hi @Samthapa76, I'm really not sure what your question is, so I'll take a stab at answering a few things.

Maybe you are trying to output to an audio file called "strings"? If that's the case you can do this : 
```
wsay "Some text" -o strings.wav
```

Or maybe you want to pipe text in wsay. To do that, you can use this style :
```
echo "strings" | wsay
```

You can take a look at the readme page examples. All the options are there. If that's not what you are trying to do, let me know.

**Comment by p-groarke** [comment]
I hope that helped, feel free to reopen if I didn't answer your question.

**Comment by Samthapa76** [comment]
hey i am sorry i was busy didn't saw your reply i got what i wanted now i am happy i got it from my friend and thanks
