### ISSUE TITLE
Option to playback to all playback devices automatically

### ISSUE THREAD

**Issue by jgstew** [p-groarke/wsay#6]
Instead of having to get the list of playback devices, parse it, then put each into the command, it would be helpful if there was a way to do:

```
wsay -p a
wsay --playback_device all
```

**Comment by p-groarke** [comment]
I like this, I'll whip it up soonish.

**Comment by p-groarke** [comment]
Fixed by https://github.com/p-groarke/wsay/releases/tag/v1.4.1 Let me know if you find any issues with it, good day.
