### ISSUE TITLE
Control the volume

### ISSUE THREAD

**Issue by mandray** [p-groarke/wsay#8]
Is there anyway to control the volume at which the audio plays?

**Comment by p-groarke** [comment]
Not right now, but it's a good feature. I'll add it.

**Comment by mandray** [comment]
Awesome, thank you! Just came across this library yesterday. It's such a great library

**Comment by p-groarke** [comment]
Thx that's very kind :) I'll let you know once it's in.

**Comment by p-groarke** [comment]
It's up, let me know if you have any issues with it.

cheers

**Comment by mandray** [comment]
I love you so much :) @p-groarke
